@hostname=localhost:4004
@domain=<domain>.authentication.ap10.hana.ondemand.com
@clientid=sb-supplier-rag-app-dev!t82402
@secret=39d9302c-...
# Define the token variable
@token=eyJhbGciOiJSU.....


### Get the auth token
GET https://{{domain}}/oauth/token?grant_type=client_credentials
Authorization: Basic {{clientid}}:{{secret}}

### Request 1 - Metadata
GET http://{{hostname}}/odata/v4/supplier-servcie/$metadata
Authorization: Bearer {{token}}

### Request 2 - Create Embedding
GET http://{{hostname}}/odata/v4/supplier-servcie/storeEmbeddings()
Authorization: Bearer {{token}}

### Request 3 - User Query
GET http://{{hostname}}/odata/v4/supplier-servcie/findSuppliers(query='Find the best suppliers in Chicago, US')
Authorization: Bearer {{token}}

### Request 4 - Validate Result
GET http://{{hostname}}/odata/v4/supplier-servcie/listSuppliers()
Authorization: Bearer {{token}}
